baseURL: https://jdhoffa.github.io
languageCode: en-us
title: Jackson Hoffart
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "My digital garden 🌱"
    Content: "Hello! My name is Jackson, here are my notes:"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/jdhoffa"
    - name: "twitter"
      url: "https://twitter.com/jdhoffart"
    - name: "kofi"
      url: "https://buymeacoffee.com/jdhoffa"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/jackson-hoffart/"
  ShowReadingTime: true
  author: "Jackson Hoffart"
  contact: "jackson.hoffart@gmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

 #Google Analytics 4 optional
  env: #production
  GoogleAnalytics: "G-JZB0EV35X5" 
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
